pipeline:
  name: Git Clone Pipeline
  identifier: git_clone
  projectIdentifier: guym_tf_project_1
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github
        repoName: pacman
        build:
          type: branch
          spec:
            branch: master
  stages:
    - stage:
        name: Clone and Run
        identifier: CloneAndRun
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: List Repository
                  identifier: List_Repository
                  spec:
                    shell: Bash
                    command: |-
                      echo "Cloned pacman @ master"
                      ls -la
                      if [ -f README.md ]; then head -20 README.md; fi
