pipeline:
  name: Build and Push Pacman
  identifier: git_clone
  projectIdentifier: guym_tf_project_1
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github
        repoName: pacman
        build:
          type: branch
          spec:
            branch: master
  stages:
    - stage:
        name: Build and Push
        identifier: BuildAndPush
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: kubernetes
              namespace: harness-delegate-ng-project
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push
                  identifier: Build_and_Push
                  spec:
                    connectorRef: account.docker_registry
                    repo: guyma6/pacman
                    tags:
                      - <+pipeline.sequenceId>
                      - latest
                    dockerfile: docker/Dockerfile
                    context: .
